#!/usr/bin/env bash

inotifywait -m -e close_write -e moved_to --format "%f" ~/Downloads |
while read -r filename; do
    case "$filename" in
    	*.txt|*.md) mv ~/Downloads/$filename ~/Downloads/text/$filename;;
        *.png|*.jpeg|*.jpg|*.bmp)
        mv ~/Downloads/$filename ~/Downloads/images/$filenames;;
	*.mp3) mv ~/Downloads/$filename ~/Downloads/music/$filename;;
	*.mp4) mv ~/Downloads/$filename ~/Downloads/videos/$filename;;
	*.docx) mv ~/Downloads/$filename ~/Downloads/documents/$filename;;
	*.pdf) mv ~/Downloads/$filename ~/Downloads/pdf/$filename;;
	*.zip) mv ~/Downloads/$filename ~/Downloads/zip/$filename;;
    *) mv ~/Downloads/$filename ~/Downloads/other/$filename;;
esac
done
