#!/usr/bin/env bash

echo "$PWD"

inotifywait -m -e close_write -e moved_to --format "%f" "$PWD" |
while read -r filename; do
    case "$filename" in
    	*.txt|*.md) mv $filename text/$filename;;
    	*.png|*.jpeg|*.jpg|*.bmp)
        mv $filename images/$filenames;;
	*.mp3) mv $filename music/$filename;;
	*.mp4) mv $filename videos/$filename;;
	*.docx) mv $filename documents/$filename;;
	*.pdf) mv $filename pdf/$filename;;
	*.zip) mv $filename zip/$filename;;
    *) mv $filename other/$filename;;
esac
done
